name: "Release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Publish Chats"
    runs-on: "ubuntu-latest"

    steps:

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Top Chats List"
          files: |
            topchats.json
